Feature branch
TahenyBELGUITH/Trial-project pull request #1
Opened 2021-07-07 12:11 UTC by TahenyBELGUITH

## trial-project

## In this project. I; 
- Added index.html file.
- Added style.css file.
- ensured there was no liters error.

2021-07-07 13:26 UTC, Davidosky007 commented
Hi @TahenyBELGUITH, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code. :pray: 

 ## Invalid CRR
_Check the comments under the review._

- [ ] You have submitted a CRR without making a review on this project using Github features[ See this article on How to give a code review](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/code-review/articles/give_code_review_basics.md) for more details

You should make sure to make reviews using GitHub inline comments.
 This Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-07-07 14:14 UTC, TahenyBELGUITH reviewed
changes required : 😊

please check my comments below  and make all required changes 

submit for re-review when you done 👍

thank you 😊

2021-07-07 14:54 UTC, mricanho requested changes
Hi @TahenyBELGUITH, 

Good job so far! 🔥🔥 You are on the way to be an excellent code reviewer!

There are some issues that you still need to work on to go to the next project but you are almost there!

 ## Required Changes ♻️

_Check the comments under the review._

- [ ] **This is a summary, you need to add it as a review, just copy and paste this format and tailored it to suit your review**

## Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

![shine team](https://user-images.githubusercontent.com/60631456/124777190-a6ba7480-df05-11eb-8f57-bc214cfdd837.gif)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-07-07 14:54 UTC, mricanho commented on index.html
> +    <title>Fork Me! FCC: Test Suite Template</title>
- [ ] Use this task list feature for every inline comment, and remember that you need to add why you require some changes, this gives a better understanding of the error for the student

2021-07-07 14:54 UTC, mricanho commented on index.html
> +</html>
- [ ]  Use this task list feature for every inline comment, and remember that you need to add why you require some changes, this gives a better understanding of the error for the student

2021-07-08 06:16 UTC, Davidosky007 requested changes
Hi @TahenyBELGUITH, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.
![cr2 gif_almost-there](https://user-images.githubusercontent.com/52497246/124871626-2a369d00-dfbc-11eb-85c8-e141c55d3a74.gif)

 ## Required Changes ♻️
* Kindly endeavour to state why you are requesting a change, i dropped hints on how to below please check comments 👍 
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2021-07-08 06:16 UTC, Davidosky007 commented on index.html
> +    <title>Fork Me! FCC: Test Suite Template</title>
* Kindly bear in mind that it is always better to clearly state why a change is required.
A more well-explained comment will be similar to:
_ Why don't you use the tag instead of a div, that would improve the HTML structure and make the page more accessible to browsers and be more meaningful to developers_

2021-07-08 06:16 UTC, Davidosky007 commented on README.md
> +# Hello-world
* Kindly state why it is important to have only one project name.
* This is an example ( Having one project name is good for SEO and helps search engines locate your webpage when been searched )

2021-07-08 13:36 UTC, Davidosky007 approved these changes
Hi @TahenyBELGUITH , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
# Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2021-07-08 13:36 UTC, Davidosky007 commented on index.html
> +    <title>Fork Me! FCC: Test Suite Template</title>
nicely done 👍

2021-07-08 14:17 UTC, merged